# Generated by Django 3.0.6 on 2020-06-08 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_num', models.IntegerField(verbose_name='Product number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('standart', models.CharField(max_length=100, verbose_name='Standart')),
                ('price', models.IntegerField(verbose_name='Retail price')),
                ('price_IJT', models.IntegerField(verbose_name='IJT price')),
                ('price_net', models.IntegerField(verbose_name='Net price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Picture')),
                ('exist', models.BooleanField(verbose_name='Exist')),
                ('sold_at', models.DateField(blank=True, null=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jewelry.Type')),
            ],
        ),
    ]
