# Generated by Django 3.0.6 on 2020-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standart',
            field=models.CharField(blank=True, max_length=100, verbose_name='Standart'),
        ),
    ]
