# Generated by Django 3.0.6 on 2020-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_auto_20200609_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Standart'),
        ),
    ]
