# Generated by Django 3.0.7 on 2020-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0004_auto_20200624_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover'),
        ),
    ]
