# Generated by Django 3.0.7 on 2020-06-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_type_type_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type_image',
        ),
    ]
