# Generated by Django 3.0.7 on 2020-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0008_remove_type_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Type cover'),
        ),
    ]
