# Generated by Django 3.0.7 on 2020-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0010_remove_type_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='cover_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
