# Generated by Django 3.0.7 on 2020-06-28 00:39

from django.db import migrations, models
import jewelry.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0012_auto_20200628_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='dummyimage.com/3456/000000/fff.png&text=Img+have+not+upload+yet', null=True, upload_to=jewelry.models.product_img_path, verbose_name='Picture'),
        ),
    ]
