# Generated by Django 3.0.7 on 2020-06-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0017_auto_20200628_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
