# Generated by Django 3.0.7 on 2020-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0023_auto_20200628_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='title_eng',
            field=models.CharField(default='Some', max_length=30, verbose_name='Title eng'),
            preserve_default=False,
        ),
    ]
