# Generated by Django 3.0.7 on 2020-07-05 09:46

from django.db import migrations


def check_exist(apps, schema_editor):
    Product = apps.get_model('jewelry', 'Product')
    for product in Product.objects.all():
        if product.quantity > 0:
            product.exist = True
        else:
            product.exist = False


class Migration(migrations.Migration):
    dependencies = [
        ('jewelry', '0030_auto_20200705_1824'),
    ]
    
    operations = [
        migrations.RunPython(check_exist)
    ]
